name: Documenter
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 'nightly'
      - run: julia --project -e 'using Pkg; Pkg.Registry.add(Pkg.RegistrySpec(url = "git@github.com:serenity4/Graphics")); Pkg.instantiate()'
      - uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
