name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['nightly']
        julia-arch: [x64]
        os: [ubuntu-latest]
        exclude:
          - os: macOS-latest
            julia-arch: x86

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - run: julia --project -e 'using Pkg; Pkg.Registry.add(Pkg.RegistrySpec(url = "git@github.com:serenity4/Graphics")); Pkg.instantiate()'
      - run: julia --project -e 'using Pkg; Pkg.test(coverage = false)'
